### ISSUE TITLE
Frontend package improvements

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/Pizzly#266]
Small improvements to make the frontend package better:
* Is `ES2022` really a good build target for frontend code? Should maybe lower this for better compatability
* The TypeScript types are not bundled in currently (although we have them)
* `bin` and `lib` folders as well as `tsconfig.json` should probably not be bundled in the released package

And more of a nice to have but maybe also solvable whilst we are at it:
* There is currently no Readme.md in the package, we could use the main Readme.md so people who discover the package in NPM have an idea what Pizzly is

**Comment by bastienbeurier** [comment]
Fixed by https://github.com/NangoHQ/Pizzly/commit/5ee00c9b6b987768b1f9b997872144bc01c95946

About the Readme, I created an issue to have Readmes for all npm packages -> https://github.com/NangoHQ/nango/issues/82
