### ISSUE TITLE
Linear /Shortcut/Clickup APP

### ISSUE THREAD

**Issue by aiseei** [NangoHQ/Pizzly#267]
Hi - would be great if you could add 3 these apps to the Pizzly suite. 

Thanks!
Aise

**Comment by rguldener** [comment]
Hi @aiseei 

Thanks for the request, I just added Linear an Clickup templates to Pizzly: https://github.com/NangoHQ/Pizzly/blob/master/packages/server/templates.yaml
If you pulled the docker image for `nangohq/pizzly-server` already please delete it and pull it again so you get the latest version which has these templates in.

For Shortcut: According to the [Shortcut API docs](https://developer.shortcut.com/api/rest/v3#Authentication) it seems to use API tokens/keys and doesn't offer OAuth? Let me know if I missed something and I am happy to add support for it as well.

Cheers,
Robin
