### ISSUE TITLE
docker compose: pizzly-server throwing error on startup

### ISSUE THREAD

**Issue by outranker** [NangoHQ/Pizzly#274]
I am trying to run Pizzly using the docker-compose.yml given in the repo but pizzly-server is not running. It throwing an error saying ```exec format error```

attached the log image
![Screen Shot 2022-12-09 at 4 04 05 PM](https://user-images.githubusercontent.com/20103472/206645441-d82622c3-71fd-4d92-927c-1155918cc1ae.png)

PostgreSQL on the other hand is starting up fine

Any help is appreciated

**Comment by bastienbeurier** [comment]
Hi! Sorry about this. 

I could not [reproduce](https://www.loom.com/share/c19f00f63d3344529977fce3d7f245bb) the issue.

Did you try to run it a 2nd time in case it was a one-time error? 

Qq: what environment are you running this on?

**Comment by outranker** [comment]
Thanks for the quick reply, @bastienbeurier !

I tried multiple times and the same error kept appearing. I am running it on Raspberry Pi  4B, 8GB RAM and its OS is Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-1074-raspi aarch64).

`docker version` command shows below output:
```
docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:03 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:22 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

P.S. I tries running it with docker compose on my Macbook Pro M1 as well as Macbook Pro Intel CPU and it worked just fine. So I think it has something to do how images are built?

**Comment by rguldener** [comment]
Hi @outranker

Thanks for posting this update, the problem is most likely that our docker images are built for the `x86_64` architecture. We currently do not build and support `arm64` images. Your M1 Mac probably masks that problem as it is translating the `x86_64` image with Rosetta to the arm instructions, but this tech is not available on Linux.

If you want to take a stab at building `arm64` images of Pizzly take a look at our build scripts in the [root level package.json](https://github.com/NangoHQ/Pizzly/blob/master/package.json) file. These should tell you how to build the project from source.
In theory I think arm64 images should be buildable with this as everything is running in Node.

Hope this helps and you find a way to run it on the Pie!

**Comment by outranker** [comment]
Hi @rguldener
Thanks for providing the answer. I think this was indeed the case. However when I tried to build it and re-run in with docker compose I am still facing an issue although different one. It says `Error: Cannot find module '/usr/pizzly-server/src/packages/server/dist/server.js'`
![Screen Shot 2022-12-10 at 12 00 21 PM](https://user-images.githubusercontent.com/20103472/206825687-106f9b72-3166-4f33-935a-24310c9a6939.png)

I am guessing it has something to do with the process of building the image. Could you please guide me in the correct direction since I think I am missing some steps in building the image.

This is what I did:
1. Cloned the [repo](https://github.com/NangoHQ/Pizzly)
2. Ran `npm i` in project root directory, `packages/cli`, `packages/frontend`, `packages/node-client` and `packages/server` directory
3. Ran `ts-build` script and then `docker-build` script

**Comment by outranker** [comment]
While writing the response above I see that the last step should've been running the scripts `ts-build` and then `build` instead of `docker-build`. After doing that containers are up and running now.

Thank you very much for the help!

**Comment by rguldener** [comment]
Awesome, great that you got it to work! 🙌
