### ISSUE TITLE
Mix of camel case and snake case in response

### ISSUE THREAD

**Issue by Simcon** [NangoHQ/Pizzly#284]
There is a mix of camel case and snake case in the response.

This makes it hard to use a deserializer since these can only utilise one method at a time (at least when it comes to .NET's System.Text.Json)

Here "accessToken" is camel whereas the rest of the output is snake:

```
{
    "id": 1,
    "created_at": "2022-12-12T18:50:14.902Z",
    "updated_at": "2022-12-12T18:50:14.902Z",
    "provider_config_key": "my-gmail",
    "connection_id": "42",
    "credentials": {
        "type": "OAUTH2",
        "accessToken": "CAMEL",
        "raw": {
            "access_token": "SNAKE",
            "expires_in": 3599,
            "scope": "https://mail.google.com/",
            "token_type": "Bearer",
            "expires_at": "2022-12-12T20:01:52.259Z"
        }
    }
}
```

The solution would be to make sure everything is snake (or camel!). This would be considered a breaking change but since the project is still young it might be acceptable to the devs.

**Comment by bastienbeurier** [comment]
Thanks for reporting this! I'll make sure there's a fix in Mondays release.

**Comment by bastienbeurier** [comment]
To get the fix, you should: 
- Use the lastest Docker container for Pizzly (^0.4.2) or Nango (^0.4.2 for server, ^0.4.3 for worker)
- update you [@nangohq/pizzly-node](https://www.npmjs.com/package/@nangohq/pizzly-node) npm package to ^0.4.1
- if you have existing Connection in the DB, your should migrate camel-case fields to snake-case in the `pizzly._pizzly_connections` table -> `credentials` column
