### ISSUE TITLE
Error when connecting LinkedIn

### ISSUE THREAD

**Issue by joanreyero** [NangoHQ/Pizzly#285]
When I try to connect the LinkedIn, Pizzly throws an error: 
<img width="1015" alt="Screenshot 2022-12-14 at 19 27 54" src="https://user-images.githubusercontent.com/37874460/207678810-60ff382b-8cdc-4fc7-9881-2e2a69563361.png">

From Discord:
_It looks like we are trying to convert an exception to JSON and that seems to contain a cicular reference - in short a bug in Pizzly
The bug only gets triggered if there is an issue in the OAuth flow though, so there is for sure also something off there_

**Comment by bastienbeurier** [comment]
I remember this was fixed a while back, but feel free to repoen if needed!
