### ISSUE TITLE
how can you access the admin UI?

### ISSUE THREAD

**Issue by ciprianm11** [NangoHQ/Pizzly#292]
This [article](https://dev.to/bearer/introducing-pizzly-an-open-sourced-free-fast-simple-api-integrations-manager-4jog ) brought me to Pizzly but im very confused about what's happening. How can i access that admin UI? 
![image](https://user-images.githubusercontent.com/121385015/209545149-a46211eb-2c5e-4c1d-b6bf-4408f353457e.png)

**Comment by rguldener** [comment]
Hi @ciprianm11 

Pizzly was recently rewritten (the old version, which you saw in the article, was abandoned). You can find more details about the rewrite here: https://github.com/NangoHQ/Pizzly/issues/263

In this new version the admin UI has been replaced with a command line CLI to configure the providers. The related documentation is here: https://docs.nango.dev/pizzly/getting-started

I hope this helps!

**Comment by rguldener** [comment]
Closing this for now, please let me know if it needs to be reopened @ciprianm11
